### ISSUE TITLE
Writing "minecraft:" suggests again something with "minecraft:"

### ISSUE THREAD

**Issue by jan00bl** [theusaf/mcfunction#13]
As example if you write "give @s minecraft:" and then use the autocomplete you would get "give @s minecraft:minecraft:acacia_bark"

**Comment by theusaf** [comment]
ive been kinda annoyed by this bug as well, but it seems to be an issue with atom. I'll look at it.

**Comment by theusaf** [comment]
Though things like minecraft:ambient.cave still has some issues that cannot really be solved:
type:
`minecraft:ambient.ca` + `<tab>` = `minecraft:ambient.ambient.cave`
This is an issue with atom and cannot be fully fixed.
