### ISSUE TITLE
pack.mcmeta

### ISSUE THREAD

**Issue by MrKleeblatt** [theusaf/mcfunction#18]
I know that you implemented text coloring, but why didn't you write `"fileTypes": ["mcfunction","mcmeta"]` in your `mcfunction13.json` and your `mcfunction.json` so that pack.mcmeta files look way better?
I just added the second tag to it on my PC and it definitely looks amazing.
...just a little "bug" or what should I call it xD
![Bild_2021-04-27_155421](https://user-images.githubusercontent.com/66536608/116253500-d49a7480-a770-11eb-8557-87e4fabe1146.png)

**Comment by theusaf** [comment]
Noted. I’ve been taking a break from this project, but I’ll consider this if I start working on it again.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
